### ISSUE TITLE
Speech recognition

### ISSUE THREAD

**Issue by jarble** [ddsky/chatbot#4]
Would it be possible to add speech recognition to this chatbot (using the [Web Speech API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Speech_API/Using_the_Web_Speech_API)) so that it can answer voice commands instead of typed commands?

**Comment by ddsky** [comment]
Sure, but that is basically only possible in Chrome and you can add that
with a simple tag to the search bar yourself.
